/* On-demand study tools; owned APIs, explicit creation and server-graded tests. */
(()=>{'use strict';
const words={en:['Mock Test','Mindmap','Close','Topic','Difficulty','Questions','Minutes','Generate and save','Creating…','Saved to your account','AI practice; check important answers.','Submit answers','Submitting…','Score','Time left','Time ended','Open saved tools','Creation continues; find the result in Study.','No answer','Correct answer','Could not finish. Your inputs are kept.','Easy','Medium','Hard'],gu:['Mock Test','Mindmap','બંધ કરો','વિષય','કઠિનતા','પ્રશ્નો','મિનિટ','બનાવો અને સાચવો','બને છે…','તમારા ખાતામાં સાચવાયું','AI અભ્યાસ; મહત્વના જવાબ તપાસો.','જવાબ મોકલો','મોકલાય છે…','ગુણ','બાકી સમય','સમય પૂરો','સાચવેલા tools ખોલો','બનાવવાનું ચાલુ છે; પરિણામ Studyમાં મળશે.','જવાબ નથી','સાચો જવાબ','પૂરું ન થયું. તમારી વિગતો યથાવત છે.','સરળ','મધ્યમ','કઠિન'],hi:['Mock Test','Mindmap','बंद करें','विषय','कठिनाई','प्रश्न','मिनट','बनाएँ और सेव करें','बन रहा है…','आपके खाते में सेव हुआ','AI अभ्यास; महत्वपूर्ण जवाब जाँचें।','जवाब भेजें','भेज रहे हैं…','अंक','बचा समय','समय पूरा','सेव किए tools खोलें','बनाना जारी है; परिणाम Study में मिलेगा।','जवाब नहीं','सही जवाब','पूरा नहीं हुआ। आपकी जानकारी सुरक्षित है।','आसान','मध्यम','कठिन']};
const node=(tag,text)=>{const el=document.createElement(tag);if(text!=null)el.textContent=text;return el};
function open({kind,api,notify=()=>{}}){if(!['mock','map'].includes(kind))return;const c=words[document.documentElement.lang]||words.en,d=node('dialog');d.className='hub-dialog chat-study-dialog';d.setAttribute('aria-label',c[kind==='mock'?0:1]);const head=node('header'),close=node('button',c[2]);close.type='button';close.className='secondary';head.append(node('h2',c[kind==='mock'?0:1]),close);d.append(head,node('p',c[10]));document.body.append(d);let creating=false,clock;close.onclick=()=>d.close();d.addEventListener('close',()=>{clearInterval(clock);if(creating)notify(c[17]);d.remove()});
const form=node('form'),status=node('p');status.setAttribute('role','status');
const field=(label,type,value)=>{const wrap=node('label',label),input=node('input');input.type=type;input.value=value||'';input.required=true;wrap.append(input);form.append(wrap);return input};
const topic=field(c[3],'text','');topic.maxLength=120;const choices=(label,items)=>{const wrap=node('label',label),select=node('select');for(const [value,text] of items){const o=node('option',text);o.value=value;select.append(o)}wrap.append(select);form.append(wrap);return select};
let difficulty,count,minutes;if(kind==='mock'){difficulty=choices(c[4],[['easy',c[21]],['medium',c[22]],['hard',c[23]]]);difficulty.value='medium';count=choices(c[5],[5,10,15,20].map(n=>[n,String(n)]));minutes=field(c[6],'number','15');minutes.min=3;minutes.max=60;minutes.step=1}
const submit=node('button',c[7]);submit.type='submit';submit.className='primary';form.append(submit);d.append(form,status);const workspace=node('a',c[16]);workspace.href='/dashboard#'+(kind==='mock'?'mocktests':'mindmaps');workspace.target='_blank';workspace.rel='noopener';workspace.className='secondary';d.append(workspace);d.showModal();
form.onsubmit=async event=>{event.preventDefault();if(creating)return;creating=true;submit.disabled=true;status.textContent=c[8];const payload={topic:topic.value,language:['en','gu','hi'].includes(document.documentElement.lang)?document.documentElement.lang:'en'};if(kind==='mock')Object.assign(payload,{difficulty:difficulty.value,question_count:Number(count.value),time_limit_minutes:Number(minutes.value)});
try{const result=await api(kind==='mock'?'/api/mock-tests/generate':'/api/mindmaps/generate',{method:'POST',body:JSON.stringify(payload)});creating=false;if(!d.isConnected){notify(c[9]);return}form.remove();status.textContent=c[9];if(kind==='map'){const map=result.mindmap?.data;if(!map?.root)throw Error(c[20]);d.append(node('p',map.summary));const root=node('section');root.className='chat-map';const branch=(data,depth=0)=>{if(depth>3)return node('p');const box=node(depth?'details':'section');if(!depth||depth===1)box.open=true;box.append(node(depth?'summary':'h3',data.label),node('p',data.desc));for(const child of (data.children||[]).slice(0,25))box.append(branch(child,depth+1));return box};root.append(branch(map.root));d.append(root)}else renderTest(result.test)}
catch(error){creating=false;if(d.isConnected){status.textContent=error.message||c[20];submit.disabled=false}}};
function renderTest(test){if(!test?.questions?.length){status.textContent=c[20];return}const exam=node('form'),timer=node('p'),notice=node('p');notice.setAttribute('role','status');timer.setAttribute('role','timer');exam.append(timer);const answers={};for(const q of test.questions){const set=node('fieldset');set.append(node('legend',q.question));for(const [letter,text] of Object.entries(q.options)){const label=node('label',letter+'. '+text),radio=node('input');radio.type='radio';radio.name='question-'+q.id;radio.value=letter;radio.onchange=()=>{answers[String(q.id)]=letter};label.prepend(radio);set.append(label)}exam.append(set)}const send=node('button',c[11]);send.type='submit';send.className='primary';exam.append(send,notice);d.append(exam);let sending=false,completed=false;const end=new Date(test.expires_at).getTime();const tick=()=>{const seconds=Math.max(0,Math.ceil((end-Date.now())/1000));timer.textContent=seconds?c[14]+': '+Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0'):c[15];if(!seconds){exam.querySelectorAll('fieldset').forEach(set=>set.disabled=true);clearInterval(clock)}};tick();clock=setInterval(tick,1000);
exam.onsubmit=async event=>{event.preventDefault();if(sending||completed)return;sending=true;send.disabled=true;notice.textContent=c[12];try{const result=await api('/api/mock-tests/'+test.id+'/submit',{method:'POST',body:JSON.stringify({answers})});completed=true;clearInterval(clock);if(!d.isConnected)return;exam.remove();d.append(node('h3',c[13]+': '+result.attempt.score+' / '+result.attempt.total_questions));for(const item of result.review){const review=node('details');review.append(node('summary',item.question),node('p',(item.user_answer||c[18])+' → '+c[19]+': '+item.correct_answer),node('p',item.explanation));d.append(review)}}catch(error){if(d.isConnected){notice.textContent=error.message||c[20];send.disabled=false}}finally{sending=false}};
}
}
window.SaathiChatStudy={open};})();
