(()=>{'use strict';let api,host;
const copy={en:{notes:'Saved notes',habits:'Active habits',study:'Study revision queue',exams:'Exam plans',context:'Chat context',explain:'Choose what future replies may read. Turning sharing off stops future access; earlier replies may still contain shared details.',tasks:'Planner tasks',reminders:'General reminders',classroom:'Selected Classroom assignments',save:'Save',close:'Close',preview:'Review before saving',title:'Title',text:'Details',time:'Date and time (your device timezone)',repeat:'Repeat',priority:'Priority',memory:'Store this general memory and use it in future replies',saved:'Saved to your account',loading:'Preparing your preview…',once:'Once',daily:'Daily',weekly:'Weekly',low:'Low',medium:'Medium',high:'High',alert:'Saving a reminder does not enable background alerts. Check Account → Background reminder alerts.',review:'Review save preview'},gu:{notes:'સાચવેલી નોંધો',habits:'સક્રિય આદતો',study:'અભ્યાસની પુનરાવર્તન યાદી',exams:'પરીક્ષાની યોજનાઓ',context:'Chat માટે માહિતી',explain:'આગળના જવાબોમાં કઈ માહિતી વાપરવી તે પસંદ કરો. બંધ કરવાથી આગળની માહિતી મળતી બંધ થાય છે; જૂના જવાબોમાં માહિતી રહી શકે.',tasks:'Plannerનાં કામ',reminders:'સામાન્ય reminders',classroom:'પસંદ કરેલા Classroom assignments',save:'સાચવો',close:'બંધ કરો',preview:'સાચવતાં પહેલાં તપાસો',title:'નામ',text:'વિગતો',time:'તારીખ અને સમય (તમારા ઉપકરણનો સમય ઝોન)',repeat:'ફરી યાદ કરાવો',priority:'પ્રાથમિકતા',memory:'આ સામાન્ય યાદ સાચવો અને આગળના જવાબોમાં વાપરો',saved:'તમારા ખાતામાં સાચવાયું',loading:'પૂર્વાવલોકન તૈયાર થાય છે…',once:'એક વાર',daily:'દરરોજ',weekly:'દર અઠવાડિયે',low:'ઓછી',medium:'મધ્યમ',high:'વધુ',alert:'Reminder સાચવવાથી background alerts ચાલુ થતા નથી. Accountમાં Background reminder alerts તપાસો.',review:'સાચવવાની વિગતો તપાસો'},hi:{notes:'सहेजे नोट्स',habits:'सक्रिय आदतें',study:'पढ़ाई की पुनरावृत्ति',exams:'परीक्षा योजनाएँ',context:'Chat की जानकारी',explain:'चुनें कि आगे के जवाब कौन सी जानकारी पढ़ सकें। बंद करने पर आगे पहुँच रुकती है; पुराने जवाबों में साझा जानकारी रह सकती है।',tasks:'Planner के काम',reminders:'सामान्य reminders',classroom:'चुने Classroom assignments',save:'सेव करें',close:'बंद करें',preview:'सेव करने से पहले जाँचें',title:'शीर्षक',text:'विवरण',time:'तारीख और समय (आपके उपकरण का समय क्षेत्र)',repeat:'दोहराएँ',priority:'प्राथमिकता',memory:'यह सामान्य याद सेव करें और आगे के जवाबों में उपयोग करें',saved:'आपके खाते में सेव हुआ',loading:'पूर्वावलोकन तैयार हो रहा है…',once:'एक बार',daily:'रोज़',weekly:'हर सप्ताह',low:'कम',medium:'मध्यम',high:'अधिक',alert:'Reminder सेव करने से background alerts चालू नहीं होते। Account में Background reminder alerts देखें।',review:'सेव का पूर्वावलोकन देखें'}};
const t=k=>(copy[document.documentElement.lang]||copy.en)[k];
const node=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e};
function shell(title){const d=node('dialog');d.className='hub-dialog';d.setAttribute('aria-label',title);const header=node('header'),h=node('h2',title),close=node('button',t('close'));close.className='secondary';close.type='button';close.onclick=()=>d.close();d.classList.add('chat-action-dialog');header.append(h,close);d.append(header);d.addEventListener('close',()=>d.remove());document.body.append(d);d.showModal();return d}
function field(parent,label,type,value,max){const l=node('label',label),e=node(type==='textarea'?'textarea':'input');if(type!=='textarea')e.type=type;e.value=value||'';if(max)e.maxLength=max;l.append(e);parent.append(l);return e}
function select(parent,label,values,value){const l=node('label',label),e=node('select');for(const v of values){const o=node('option',t(v));o.value=v;e.append(o)}e.value=value;l.append(e);parent.append(l);return e}
async function context(){const d=shell(t('context')),status=node('p',t('loading'));status.setAttribute('role','status');d.append(node('p',t('explain')),status);try{const data=await api('/api/chat-context');if(!d.isConnected)return;status.textContent='';const inputs={};for(const k of ['tasks','reminders','classroom','notes','habits','study','exams']){const l=node('label',t(k)),e=node('input');e.type='checkbox';e.checked=data.permissions[k];l.prepend(e);d.append(l);inputs[k]=e}const save=node('button',t('save'));save.className='primary';d.append(save);save.onclick=async()=>{save.disabled=true;try{await api('/api/chat-context',{method:'PATCH',body:JSON.stringify(Object.fromEntries(Object.entries(inputs).map(([key,input])=>[key,input.checked])))});status.textContent=t('saved')}catch(e){status.textContent=e.message}finally{save.disabled=false}}}catch(e){status.textContent=e.message}}
async function preview(message,button){const d=shell(t('preview')),status=node('p',t('loading'));status.setAttribute('role','status');d.append(status);try{const data=await api('/api/chat-actions/'+message.id);if(!d.isConnected)return;if(data.saved){status.textContent=t('saved');button.textContent=t('saved');return}status.textContent='';const a=data.action,form=node('form');d.append(form);const title=field(form,t('title'),'text',a.title,{task:180,reminder:160,note:80,memory:80,habit:120,journal:120,checkin:100}[a.kind]);title.required=true;const text=field(form,t('text'),'textarea',a.text,{task:1000,reminder:500,note:10000,memory:1000,habit:0,journal:20000,checkin:1000}[a.kind]);text.required=['note','memory','journal'].includes(a.kind);if(a.kind==='habit')text.parentElement.hidden=true;if(a.kind==='checkin')title.parentElement.hidden=true;let time,repeat,priority,consent,mood,energy,entryDate;const extra={en:['Mood (1–5)','Energy (1–5)','Entry date'],gu:['મનોભાવ (1–5)','ઊર્જા (1–5)','નોંધની તારીખ'],hi:['मनोदशा (1–5)','ऊर्जा (1–5)','प्रविष्टि की तारीख']}[document.documentElement.lang]||['Mood (1–5)','Energy (1–5)','Entry date'];if(a.kind==='checkin'){mood=field(form,extra[0],'number',a.mood);energy=field(form,extra[1],'number',a.energy);for(const e of [mood,energy]){e.min=1;e.max=5;e.step=1;e.required=true}}if(a.kind==='journal'){entryDate=field(form,extra[2],'date',a.entry_date);entryDate.required=true}if(a.kind==='habit')repeat=select(form,t('repeat'),['daily','weekly'],a.recurrence);
if(['task','reminder'].includes(a.kind)){const date=a.at?new Date(a.at):null;time=field(form,t('time')+' · '+Intl.DateTimeFormat().resolvedOptions().timeZone,'datetime-local',date?new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16):'');time.required=a.kind==='reminder'}
if(a.kind==='reminder'){repeat=select(form,t('repeat'),['once','daily','weekly'],a.recurrence);form.append(node('p',t('alert')))}if(a.kind==='task')priority=select(form,t('priority'),['low','medium','high'],a.priority);if(a.kind==='memory'){const l=node('label',t('memory'));consent=node('input');consent.type='checkbox';consent.required=true;l.prepend(consent);form.append(l)}const save=node('button',t('save'));save.type='submit';save.className='primary';form.append(save);let saving=false;form.onsubmit=async e=>{e.preventDefault();if(saving)return;saving=true;save.disabled=true;try{await api('/api/chat-actions/'+message.id,{method:'POST',body:JSON.stringify({confirmed:true,memory_consent:!!consent?.checked,action:{...a,title:title.value,text:text.value,at:time?.value?new Date(time.value).toISOString():null,recurrence:repeat?.value||a.recurrence,priority:priority?.value||a.priority,...(mood?{mood:Number(mood.value),energy:Number(energy.value)}:{}),...(entryDate?{entry_date:entryDate.value}:{})}})});status.textContent=t('saved');button.textContent=t('saved');form.remove()}catch(error){status.textContent=error.message}finally{saving=false;save.disabled=false}}}catch(e){status.textContent=e.message}}
function attach(body,message){if(!String(message.content).includes('<SAATHI_ACTION>')||message.failed||message.streaming)return;const b=node('button',t('review'));b.type='button';b.className='message-tool';b.onclick=()=>preview(message,b);body.append(b)}
const toolsCopy={en:['Tools','In this chat','Save with a preview','Open workspace · keeps chat open','Explain','Deep study','Summary','Quiz','Flashcards','Study plan','Care conversation','Add a task','Add a reminder','Save a note','Add a habit','Write a journal entry','Check in','Save a memory','Today','Planner','Reminders','Habits','Journal','Check-ins','Study & Classroom','Mock tests','Mindmaps','Care & food plans','Memory','Family Bridge','Account & alerts','Focus timer','Search','Photo / PDF','Keep or send your current draft first.','Finish or stop the current reply first.'],gu:['Tools','આ Chatમાં','પૂર્વાવલોકન સાથે સાચવો','Workspace ખોલો · Chat ખુલ્લી રહેશે','સમજાવો','ઊંડો અભ્યાસ','સારાંશ','Quiz','Flashcards','અભ્યાસ યોજના','સંભાળની વાત','કામ ઉમેરો','Reminder ઉમેરો','નોંધ સાચવો','આદત ઉમેરો','Journal લખો','Check-in કરો','યાદ સાચવો','આજનો દિવસ','Planner','Reminders','આદતો','Journal','Check-ins','અભ્યાસ અને Classroom','Mock tests','Mindmaps','સંભાળ અને ભોજન યોજના','યાદો','Family Bridge','ખાતું અને alerts','Focus timer','શોધો','ફોટો / PDF','પહેલાં હાલનો draft સાચવો અથવા મોકલો.','પહેલાં હાલનો જવાબ પૂરો થવા દો અથવા રોકો.'],hi:['Tools','इस Chat में','पूर्वावलोकन के साथ सेव करें','Workspace खोलें · Chat खुली रहेगी','समझाएँ','गहरा अध्ययन','सारांश','Quiz','Flashcards','पढ़ाई की योजना','देखभाल की बातचीत','काम जोड़ें','Reminder जोड़ें','नोट सेव करें','आदत जोड़ें','Journal लिखें','Check-in करें','याद सेव करें','आज','Planner','Reminders','आदतें','Journal','Check-ins','पढ़ाई और Classroom','Mock tests','Mindmaps','देखभाल और भोजन योजना','यादें','Family Bridge','खाता और alerts','Focus timer','खोजें','फोटो / PDF','पहले वर्तमान draft सेव करें या भेजें।','पहले वर्तमान जवाब पूरा होने दें या रोकें।']};
let planningAssets;
function loadPlanning(){if(!planningAssets)planningAssets=Promise.all([['link','/daily-workspace.css?v=20260927c'],['script','/personal-context.js?v=20261009d']].map(([tag,url])=>new Promise((resolve,reject)=>{const asset=node(tag);if(tag==='link'){asset.rel='stylesheet';asset.href=url}else asset.src=url;asset.onload=resolve;asset.onerror=()=>{asset.remove();reject(new Error(({gu:'Tool લોડ ન થયું. ફરી પ્રયત્ન કરો.',hi:'Tool लोड नहीं हुआ। फिर कोशिश करें।'}[document.documentElement.lang]||'Tool could not load. Try again.')))};document.head.append(asset)}))).catch(error=>{planningAssets=null;throw error});return planningAssets}
async function examTool(){const title=({gu:'પરીક્ષાની તૈયારી યોજના',hi:'परीक्षा की तैयारी योजना'}[document.documentElement.lang]||'Plan for an exam'),d=shell(title),status=node('p',t('loading'));status.setAttribute('role','status');d.append(status);const open=async()=>{try{status.textContent=t('loading');await loadPlanning();if(!d.isConnected)return;d.close();window.SaathiPersonal.openExams({api,notify:host.notify||(()=>{}),openView:()=>{},refreshTasks:async()=>{}})}catch(error){if(!d.isConnected)return;status.textContent=error.message;if(!d.querySelector('[data-planning-retry]')){const retry=node('button',({gu:'ફરી પ્રયત્ન કરો',hi:'फिर कोशिश करें'}[document.documentElement.lang]||'Retry'));retry.type='button';retry.className='secondary';retry.dataset.planningRetry='';retry.onclick=()=>{retry.remove();open()};d.append(retry)}}};await open()}
function tools(){const c=toolsCopy[document.documentElement.lang]||toolsCopy.en,d=shell(c[0]);d.classList.add('chat-tools-dialog');
const group=(title,collapsed=false)=>{const section=node(collapsed?'details':'section');section.append(node(collapsed?'summary':'h3',title));const grid=node('div');grid.className='chat-tools-grid';section.append(grid);d.append(section);return grid};
const button=(grid,label,run)=>{const b=node('button',label);b.type='button';b.className='secondary';b.onclick=()=>{d.close();run()};grid.append(b);return b};
const modes=group(c[1]);['explain','deep_study','summarise','quiz','flashcards','study_plan','care'].forEach((mode,i)=>{const b=button(modes,c[i+4],()=>host.chooseMode(mode));b.disabled=!host.modes().includes(mode)});
button(modes,({gu:'સ્વાસ્થ્ય અને સુખાકારી',hi:'स्वास्थ्य और भलाई'}[document.documentElement.lang]||'Wellbeing'),()=>host.chooseMode('healer')).disabled=!host.modes().includes('healer');
const save=group(c[2],true);['task','reminder','note','habit','journal','checkin','memory'].forEach((kind,i)=>button(save,c[i+11],()=>host.prepare(kind)));
const quick=group(({gu:'ઝડપી tools',hi:'त्वरित tools'}[document.documentElement.lang]||'Quick tools'));button(quick,c[31],()=>window.SaathiHub?.focus());button(quick,c[32],()=>window.SaathiHub?.search());const attach=button(quick,c[33],()=>document.getElementById('attachButton')?.click());attach.disabled=!!document.getElementById('attachButton')?.disabled;
button(quick,t('context'),context);button(quick,({gu:'પરીક્ષાની તૈયારી યોજના',hi:'परीक्षा की तैयारी योजना'}[document.documentElement.lang]||'Plan for an exam'),examTool);button(quick,t('notes'),()=>window.SaathiWorkspace?.openNotes());
const links=group(c[3],true);['overview','tasks','reminders','habits','journal','checkins','study','mocktests','mindmaps','healer','memory','family','account'].forEach((view,i)=>{const a=node('a',c[18+i]);a.className='secondary';a.href='/dashboard#'+view;a.target='_blank';a.rel='noopener';links.append(a)});
}
function connect(options){api=options.api;host=options;const top=document.querySelector(".top-actions");if(top){const b=node("button");b.type="button";b.className="chat-tools-trigger";const update=()=>{const title=(toolsCopy[document.documentElement.lang]||toolsCopy.en)[0];b.textContent=title;b.setAttribute("aria-label",title)};update();b.onclick=tools;top.prepend(b);new MutationObserver(update).observe(document.documentElement,{attributes:true,attributeFilter:["lang"]})}const parent=document.querySelector('.composer-toolbar')||document.querySelector('.composer')||document.getElementById('chatInput')?.parentElement;if(parent){const b=node('button',t('context'));b.type='button';b.className='message-tool';b.title=t('context');b.setAttribute('aria-label',t('context'));b.onclick=context;parent.append(b);new MutationObserver(()=>{b.textContent=t('context');b.title=t('context');b.setAttribute('aria-label',t('context'))}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']})}}
function clean(text){return String(text||'').replace(/<SAATHI_ACTION>[\s\S]*$/,'').replace(/<(?:S|SA|SAA|SAAT|SAATH|SAATHI|SAATHI_|SAATHI_A|SAATHI_AC|SAATHI_ACT|SAATHI_ACTI|SAATHI_ACTIO|SAATHI_ACTION)?$/,'').trimEnd()}
window.SaathiChatActions={connect,attach,clean};})();
