/* Selected coursework imports; AI only with separate selected-assignment consent. */
(function(){
'use strict';let api,notify,refreshTasks,callbackResult;
const words={
autoOff:['Automatic refresh is not available yet. Use Sync selected courses.','આપોઆપ refresh હજી ઉપલબ્ધ નથી. પસંદ કરેલા courses sync કરો.','अपने आप अपडेट अभी उपलब्ध नहीं है। चुने पाठ्यक्रम सिंक करें।'],
callbackPermissions:['Google did not grant both required permissions. Connect again and review both Classroom read permissions.','Googleએ બંને જરૂરી મંજૂરી આપી નથી. ફરી જોડો અને Classroomની બંને વાંચવાની મંજૂરી તપાસો.','Google ने दोनों आवश्यक अनुमतियाँ नहीं दीं। फिर जुड़ें और Classroom की दोनों पढ़ने की अनुमतियाँ जाँचें।'],
callbackExpired:['This connection expired. Start Connect again.','આ જોડાણની સમયમર્યાદા પૂરી થઈ. ફરી Connect કરો.','इस कनेक्शन का समय समाप्त हुआ। फिर Connect करें।'],
callbackCancelled:['Connection was cancelled. Your saved work stays available.','જોડાણ રદ થયું. સાચવેલું કામ ઉપલબ્ધ છે.','कनेक्शन रद्द हुआ। सहेजा काम उपलब्ध है।'],
callbackFailed:['Google could not finish the connection. Review the selected account and try Connect again.','Google જોડાણ પૂરું કરી શક્યું નહીં. પસંદ કરેલું account તપાસીને ફરી જોડો.','Google कनेक्शन पूरा नहीं कर सका। चुना खाता जाँचकर फिर जुड़ें।'],
working:['Working… please keep this window open.','કામ ચાલુ છે… આ વિન્ડો ખુલ્લી રાખો.','काम जारी है… यह विंडो खुली रखें।'],
schedule:['Refresh my selected courses about every six hours. Updates can be delayed. Changing courses turns this off.','પસંદ કરેલા courses લગભગ દર છ કલાકે refresh કરો. અપડેટ મોડા પડી શકે. Courses બદલવાથી આ બંધ થાય છે.','चुने पाठ्यक्रम लगभग हर छह घंटे अपडेट करें। अपडेट में देर हो सकती है। पाठ्यक्रम बदलने पर यह बंद होता है।'],scheduleSave:['Save sync preference','Sync પસંદગી સેવ કરો','सिंक पसंद सेव करें'],aiConsent:['Send only this assignment to the AI provider for an explanation. No profile, memory or other assignments.','સમજાવવા માટે ફક્ત આ અસાઇનમેન્ટ AIને મોકલો. Profile, memory કે બીજી અસાઇનમેન્ટ નહીં.','समझाने के लिए केवल यह असाइनमेंट AI को भेजें। Profile, memory या अन्य असाइनमेंट नहीं।'],explain:['Explain requirements and steps','જરૂરિયાત અને પગલાં સમજાવો','आवश्यकताएँ और चरण समझाएँ'],aiLimit:['AI can misunderstand. Check requirements and deadlines in the original; nothing is submitted or saved.','AI ભૂલ કરી શકે. મૂળમાં જરૂરિયાત અને છેલ્લી તારીખ તપાસો; કંઈ submit કે સેવ થતું નથી.','AI गलत समझ सकता है। मूल में आवश्यकताएँ और समयसीमा जाँचें; कुछ submit या सेव नहीं होता।'],
refresh:['Refresh course list','Coursesની યાદી ફરી જુઓ','पाठ्यक्रम सूची ताज़ा करें'],syncError:['The last sync failed. Your previous assignments remain available.','છેલ્લું sync નિષ્ફળ થયું. જૂની અસાઇનમેન્ટ ઉપલબ્ધ છે.','अंतिम सिंक असफल रहा। पुराने असाइनमेंट उपलब्ध हैं।'],open:['Google Classroom','Google Classroom','Google Classroom'],close:['Close','બંધ કરો','बंद करें'],connect:['Connect Classroom','Classroom જોડો','Classroom जोड़ें'],off:['Classroom connection is not configured yet. Your other study tools remain available.','Classroom કનેક્શન હજી તૈયાર નથી. બીજાં અભ્યાસ સાધનો ઉપલબ્ધ છે.','Classroom कनेक्शन अभी तैयार नहीं है। अन्य अध्ययन साधन उपलब्ध हैं।'],
notice:['Separate from Google login. Import only selected courses where you are a student. No classmates, grades, messages or automatic submissions are imported. Only an assignment you select with separate permission is sent to AI. Planner completion is not official submission.','Google loginથી અલગ. તમે વિદ્યાર્થી હો તે પસંદ કરેલા courses જ આયાત થાય છે. સહાધ્યાયીઓ, ગુણ, સંદેશા કે આપોઆપ submission નહીં. અલગ સંમતિથી પસંદ કરેલી અસાઇનમેન્ટ જ AIને મોકલાય છે. Plannerમાં પૂરું કરવું એટલે સત્તાવાર submission નહીં.','Google login से अलग। केवल चुने पाठ्यक्रम जहाँ आप छात्र हैं। सहपाठियों, अंकों, संदेशों या स्वतः सबमिशन का आयात नहीं। अलग अनुमति से चुना असाइनमेंट ही AI को भेजा जाता है। Planner में पूरा करना आधिकारिक सबमिशन नहीं है।'],
consent:['I agree to connect and store selected assignment information.','પસંદ કરેલી અસાઇનમેન્ટ માહિતી જોડવા અને સંગ્રહની મંજૂરી આપું છું.','चुने असाइनमेंट की जानकारी जोड़ने और रखने की अनुमति देता/देती हूँ।'],courses:['Choose up to three courses','ત્રણ સુધી courses પસંદ કરો','अधिकतम तीन पाठ्यक्रम चुनें'],save:['Save selection','પસંદગી સેવ કરો','चयन सेव करें'],sync:['Sync selected courses','પસંદ કરેલા courses sync કરો','चुने पाठ्यक्रम सिंक करें'],last:['Last successful sync','છેલ્લું સફળ sync','अंतिम सफल सिंक'],never:['Not synced yet','હજી sync નથી','अभी सिंक नहीं हुआ'],stale:['Imported information may be old. Sync to check changes.','આયાત કરેલી માહિતી જૂની હોઈ શકે. ફેરફાર માટે sync કરો.','आयात की जानकारी पुरानी हो सकती है। बदलाव देखने के लिए सिंक करें।'],
noDue:['No confirmed deadline','નક્કી કરેલી છેલ્લી તારીખ નથી','पक्की समयसीमा नहीं'],unavailable:['No longer listed; check Classroom','હવે યાદીમાં નથી; Classroom તપાસો','अब सूची में नहीं; Classroom देखें'],original:['Open original','મૂળ ખોલો','मूल खोलें'],planner:['Add to Planner','Plannerમાં ઉમેરો','Planner में जोड़ें'],added:['Already in Planner','Plannerમાં ઉમેરેલું છે','Planner में पहले से है'],empty:['No selected assignments yet. Choose courses and sync.','હજી પસંદ કરેલી અસાઇનમેન્ટ નથી. Courses પસંદ કરી sync કરો.','अभी चुने असाइनमेंट नहीं हैं। पाठ्यक्रम चुनकर सिंक करें।'],disconnect:['Disconnect','જોડાણ બંધ કરો','कनेक्शन हटाएँ'],remove:['Also remove imported assignments. Planner tasks stay.','આયાત કરેલી અસાઇનમેન્ટ પણ કાઢો. Plannerના કામ રહેશે.','आयात असाइनमेंट भी हटाएँ। Planner के काम रहेंगे।'],confirm:['Confirm','પુષ્ટિ કરો','पुष्टि करें'],revoke:['Disconnected locally. Google revocation could not be verified; remove access in your Google account too.','અહીં જોડાણ બંધ થયું. Google access દૂર થયાની ચકાસણી થઈ નથી; Google accountમાં પણ access દૂર કરો.','यहाँ कनेक्शन हट गया। Google access हटने की पुष्टि नहीं हुई; Google खाते में भी access हटाएँ।'],retry:['Retry','ફરી પ્રયાસ કરો','फिर कोशिश करें'],saved:['Saved','સેવ થયું','सेव हुआ']
};
const t=k=>words[k][({en:0,gu:1,hi:2})[document.documentElement.lang]||0];
function node(tag,value,cls){const n=document.createElement(tag);if(value)n.textContent=value;if(cls)n.className=cls;return n}
function button(label,fn){const b=node('button',label,'dw-button');b.type='button';b.onclick=fn;return b}
function check(label){const wrap=node('label',null,'dw-check'),el=node('input');el.type='checkbox';wrap.append(el,node('span',label));return{wrap,el}}
async function open(){
 const d=node('dialog',null,'dw-dialog');d.setAttribute('data-user-content','');d.style.overflowWrap='anywhere';const title=node('h2',t('open'));title.id='classroom-'+crypto.randomUUID();d.setAttribute('aria-labelledby',title.id);d.append(title,button(t('close'),()=>{if(!d.dataset.saving)d.close()}),node('p',t('notice'),'dw-muted'));const error=node('p',null,'dw-error');error.setAttribute('role','alert');const body=node('div');const progress=node('p',null,'dw-muted');progress.setAttribute('role','status');d.append(error,progress,body);document.body.append(d);d.showModal();d.addEventListener('close',()=>d.remove());d.addEventListener('cancel',e=>{if(d.dataset.saving)e.preventDefault()});let busy=false;
 async function run(fn){if(busy)return;busy=true;d.dataset.saving='true';d.setAttribute('aria-busy','true');progress.textContent=t('working');const controls=[...d.querySelectorAll('button,input,select,textarea')].map(n=>[n,n.disabled]);controls.forEach(([n])=>n.disabled=true);error.textContent='';try{await fn()}catch(e){error.textContent=e.message}finally{busy=false;delete d.dataset.saving;d.removeAttribute('aria-busy');progress.textContent='';controls.forEach(([n,v])=>n.disabled=v)}}
 const post=(path,data)=>api('/api/classroom/'+path,{method:'POST',body:JSON.stringify({confirmed:true,...data})});
 function confirmButton(label,fn){let ready=false;const b=button(label,()=>{if(!ready){ready=true;b.textContent=t('confirm')+': '+label;return}run(fn)});return b}
 async function load(){
  const status=await api('/api/classroom/status');if(!d.isConnected)return;body.replaceChildren();if(!status.configured&&!status.connected){body.append(node('p',t('off')));return}
  if(!status.connected){const consent=check(t('consent'));body.append(consent.wrap,button(t('connect'),()=>run(async()=>{if(!consent.el.checked){error.textContent=t('consent');return}const r=await post('connect',{});const u=new URL(r.url);if(u.origin!=='https://accounts.google.com')throw new Error('Invalid connection link');location.assign(u.href)})));return}
  if(!status.configured){const remove=check(t('remove'));body.append(node('p',t('off')),remove.wrap,confirmButton(t('disconnect'),async()=>{await post('disconnect',{remove_imports:remove.el.checked});await load()}));return}
  body.append(node('p',t('last')+': '+(status.connection.last_sync?new Date(status.connection.last_sync).toLocaleString(document.documentElement.lang):t('never'))),node('p',t('stale'),'dw-muted'));
  if(status.connection.last_error)body.append(node('p',t('syncError'),'dw-error'));
  const courses=await api('/api/classroom/courses');if(!d.isConnected)return;const choices=node('fieldset'),legend=node('legend',t('courses'));choices.append(legend);const entries=[];for(const c of courses.courses){const entry=check(c.name);entry.el.checked=courses.selected.includes(c.id);entries.push([c.id,entry]);choices.append(entry.wrap)}body.append(button(t('refresh'),()=>run(async()=>{await api('/api/classroom/courses?refresh=1');await load()})),choices,button(t('save'),()=>run(async()=>{await post('select',{courses:entries.filter(([,c])=>c.el.checked).map(([id])=>id),version:courses.version});await load()})),button(t('sync'),()=>run(async()=>{await post('sync',{});await load()})));
  if(status.scheduler_ready||status.connection.auto_sync_enabled){const auto=check(t('schedule'));auto.el.checked=!!status.connection.auto_sync_enabled;if(!status.scheduler_ready){auto.el.disabled=true;body.append(node('p',t('autoOff'),'dw-muted'),button(t('scheduleSave'),()=>run(async()=>{await post('schedule',{enabled:false,version:status.connection.version});await load()})))}else body.append(auto.wrap,button(t('scheduleSave'),()=>run(async()=>{await post('schedule',{enabled:auto.el.checked,version:status.connection.version});await load()})));}else body.append(node('p',t('autoOff'),'dw-muted'));
  const data=await api('/api/classroom/assignments');if(!d.isConnected)return;if(!data.assignments.length)body.append(node('p',t('empty'),'dw-muted'));
  for(const a of data.assignments){const row=node('article',null,'dw-panel');row.append(node('h3',a.title),node('p',a.instructions),node('p',a.due_at?new Date(a.due_at).toLocaleString(document.documentElement.lang):t('noDue')));if(!a.available)row.append(node('p',t('unavailable'),'dw-muted'));if(a.original_url){const link=node('a',t('original'),'dw-button');link.href=a.original_url;link.target='_blank';link.rel='noopener noreferrer';row.append(link)}if(a.available&&!a.task_id)row.append(confirmButton(t('planner'),async()=>{await post('assignments/'+a.id+'/planner',{});await refreshTasks();await load()}));else if(a.task_id)row.append(node('small',t('added')));if(a.available){const consent=check(t('aiConsent')),output=node('p');row.append(consent.wrap,button(t('explain'),()=>run(async()=>{if(!consent.el.checked)throw new Error(t('aiConsent'));const r=await post('assignments/'+a.id+'/explain',{ai_confirmed:true,language:document.documentElement.lang});output.textContent=r.explanation})),node('p',t('aiLimit'),'dw-muted'),output)}body.append(row)}
  const remove=check(t('remove'));body.append(remove.wrap,confirmButton(t('disconnect'),async()=>{const result=await post('disconnect',{remove_imports:remove.el.checked});notify(result.revoked?t('saved'):t('revoke'));await load()}));
 }
 progress.textContent=t('working');try{await load();if(callbackResult){error.textContent=t(callbackResult);callbackResult=null}}catch(e){error.textContent=e.message;body.append(button(t('retry'),()=>run(load)))}finally{progress.textContent=''}
}
function labels(){document.querySelectorAll('[data-classroom]').forEach(b=>b.textContent=t('open'))}
function connect(options){({api,notify,refreshTasks}=options);document.querySelectorAll('[data-classroom]').forEach(b=>b.onclick=open);labels();const url=new URL(location.href),result=url.searchParams.get('classroom_result');if(result){callbackResult=({missing_classroom_permissions:'callbackPermissions',expired:'callbackExpired',cancelled:'callbackCancelled'})[result]||'callbackFailed';url.searchParams.delete('classroom_result');history.replaceState(history.state,'',url.pathname+url.search+url.hash);open()}}
new MutationObserver(labels).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});window.SaathiClassroom={connect};
})();
