/* Optional context and preview-first study planning; no automatic AI calls. */
(function(){
'use strict';
let api,notify,openView,refreshTasks;
const words={
gentle:['Gentle','સૌમ્ય','सौम्य'],direct:['Direct and respectful','સીધી અને આદરપૂર્ણ','सीधी और सम्मानपूर्ण'],
replan:['Reschedule missed blocks','બાકી અભ્યાસ ફરી ગોઠવો','छूटे अध्ययन का समय बदलें'],progress:['I have reviewed completed work in Planner.','મેં Plannerમાં પૂરાં થયેલાં કામ તપાસ્યાં છે.','मैंने Planner में पूरे काम की समीक्षा की है।'],replanNote:['Untouched overdue blocks move. Changing the confirmed exam date also reschedules untouched future blocks. Completed and manually edited tasks stay unchanged. Other saved exam blocks reserve this plan’s daily budget too; review undated blocks and other commitments in Planner. No new tasks or AI calls.','ન બદલેલા બાકી કામ ખસેડાશે. પરીક્ષાની તારીખ બદલો તો ન બદલેલા ભાવિ કામ પણ ફરી ગોઠવાશે. પૂરાં કે જાતે બદલેલાં કામ યથાવત રહેશે. બીજી પરીક્ષા યોજનાના કામ પણ સમયના બજેટમાં ગણાશે; તારીખ વગરનાં અને બીજાં કામ Plannerમાં તપાસો. નવા કામ કે AI કૉલ નહીં.','बिना बदलाव वाले छूटे काम खिसकेंगे। परीक्षा की तारीख बदलने पर बिना बदलाव वाले आगे के काम भी फिर तय होंगे। पूरे और स्वयं बदले काम वैसे रहेंगे। दूसरी परीक्षा योजनाओं के काम भी समय सीमा में गिने जाएँगे; बिना तारीख वाले और अन्य काम Planner में देखें। नए काम या AI कॉल नहीं।'],applyReplan:['Confirm new dates','નવી તારીખોની પુષ્ટિ કરો','नई तारीखें पक्की करें'],unscheduled:['Blocks without space before the rest day','આરામના દિવસ પહેલાં જગ્યા ન મળેલા કામ','आराम के दिन से पहले समय न मिले काम'],outsideWindow:['Review manually edited blocks on or after the rest day','આરામના દિવસે કે પછીનાં જાતે બદલેલા કામ તપાસો','आराम के दिन या उसके बाद के स्वयं बदले काम देखें'],preserved:['Manually edited blocks kept','જાતે બદલેલા કામ યથાવત','स्वयं बदले काम सुरक्षित'],noMoves:['No eligible blocks to move.','ખસેડવા યોગ્ય કામ નથી.','बदलने योग्य काम नहीं हैं।'],

care:['Care profile','સંભાળ પ્રોફાઇલ','देखभाल प्रोफ़ाइल'],study:['Study profile','અભ્યાસ પ્રોફાઇલ','पढ़ाई प्रोफ़ाइल'],profile:['Personal context','વ્યક્તિગત માહિતી','व्यक्तिगत जानकारी'],optional:['Optional, with your permission','વૈકલ્પિક, તમારી મંજૂરીથી','वैकल्पिक, आपकी अनुमति से'],review:['Review','જુઓ','देखें'],exams:['Plan for an exam','પરીક્ષાની તૈયારી યોજના','परीक्षा की तैयारी योजना'],close:['Close','બંધ કરો','बंद करें'],save:['Save','સેવ કરો','सेव करें'],remove:['Delete','કાઢી નાખો','हटाएँ'],retry:['Retry','ફરી પ્રયાસ કરો','फिर कोशिश करें'],loading:['Loading…','લોડ થઈ રહ્યું છે…','लोड हो रहा है…'],saved:['Saved.','સેવ થયું.','सेव हुआ।'],deleted:['Deleted.','કાઢી નાખ્યું.','हटा दिया।'],
conditions:['Conditions you report','તમે જણાવેલી આરોગ્ય સ્થિતિ','आपकी बताई स्वास्थ्य स्थितियाँ'],allergies:['Allergies you report','તમે જણાવેલી એલર્જી','आपकी बताई एलर्जी'],clinician_instructions:['Instructions you enter from your clinician','તમે લખેલી ડોક્ટરની સૂચનાઓ','आपके लिखे चिकित्सक के निर्देश'],food_preferences:['Food preferences and budget','ખોરાકની પસંદગી અને બજેટ','भोजन की पसंद और बजट'],accessibility:['Accessibility preferences','સુલભતાની પસંદગી','सुगमता की पसंद'],level:['Study level','અભ્યાસનું સ્તર','पढ़ाई का स्तर'],subjects:['Subjects','વિષયો','विषय'],goal:['Study goal','અભ્યાસનું લક્ષ્ય','पढ़ाई का लक्ष्य'],available_time:['Available study time','અભ્યાસ માટેનો સમય','पढ़ाई के लिए समय'],tone:['Preferred tone','વાતચીતની પસંદગી','बातचीत की पसंद'],
private:['Stored privately; excluded from AI','ખાનગી સંગ્રહ; AIને મોકલાતું નથી','निजी संग्रह; AI को नहीं भेजा जाता'],permitted:['Permitted for relevant AI mode','સંબંધિત AI મોડ માટે મંજૂરી છે','संबंधित AI मोड के लिए अनुमति है'],confirm:['I confirm this information and agree to store it in my account.','આ માહિતીની પુષ્ટિ કરું છું અને મારા એકાઉન્ટમાં સંગ્રહની મંજૂરી આપું છું.','मैं जानकारी की पुष्टि और अपने खाते में इसके संग्रह की अनुमति देता/देती हूँ।'],allow:['Allow this field in relevant AI replies','સંબંધિત AI જવાબમાં આ માહિતી વાપરવાની મંજૂરી','संबंधित AI जवाबों में इस जानकारी के उपयोग की अनुमति'],
boundary:['Off by default. Care fields are sent only in Wellbeing mode; study fields only in study modes. The configured AI provider processes permitted fields. Nothing is shared with caregivers. Review every 90 days; older fields are excluded.','મૂળભૂત રીતે બંધ. સંભાળની માહિતી ફક્ત સુખાકારી મોડમાં અને અભ્યાસની માહિતી અભ્યાસ મોડમાં મોકલાય છે. મંજૂર માહિતી AI સેવા પ્રોસેસ કરે છે. સંભાળ રાખનાર સાથે શેર થતી નથી. દર 90 દિવસે તપાસો; જૂની માહિતી મોકલાતી નથી.','शुरू में बंद। देखभाल की जानकारी केवल स्वास्थ्य मोड और पढ़ाई की जानकारी अध्ययन मोड में भेजी जाती है। अनुमत जानकारी AI सेवा प्रोसेस करती है। देखभाल करने वालों से साझा नहीं होती। हर 90 दिन में जाँचें; पुरानी जानकारी नहीं भेजी जाती।'],
source:['Source: you. Clinician instructions are entered by you, not independently verified.','સ્ત્રોત: તમે. ડોક્ટરની સૂચનાઓ તમે લખી છે; સ્વતંત્ર ચકાસણી થઈ નથી.','स्रोत: आप। चिकित्सक के निर्देश आपने लिखे हैं; स्वतंत्र सत्यापन नहीं हुआ है।'],revoke:['Stop all profile use in AI','પ્રોફાઇલનો AIમાં ઉપયોગ બંધ કરો','प्रोफ़ाइल का AI में उपयोग बंद करें'],revoked:['Future profile use in AI stopped. Previously sent information cannot be recalled.','હવે પ્રોફાઇલ AIને મોકલાશે નહીં. અગાઉ મોકલેલી માહિતી પાછી ખેંચી શકાતી નથી.','आगे प्रोफ़ाइल AI को नहीं भेजी जाएगी। पहले भेजी जानकारी वापस नहीं ली जा सकती।'],last:['Last reviewed','છેલ્લી તપાસ','अंतिम समीक्षा'],empty:['Not saved','સેવ નથી','सेव नहीं है'],deleteConfirm:['Confirm deletion','કાઢવાની પુષ્ટિ કરો','हटाने की पुष्टि करें'],
title:['Exam name','પરીક્ષાનું નામ','परीक्षा का नाम'],date:['Confirmed exam date','નક્કી કરેલી પરીક્ષાની તારીખ','परीक्षा की पक्की तारीख'],topics:['Topics, one per line','દરેક લાઇનમાં એક મુદ્દો','हर पंक्ति में एक विषय'],minutes:['Available minutes per day','દરરોજ ઉપલબ્ધ મિનિટ','रोज उपलब्ध मिनट'],zone:['Timezone','સમયક્ષેત્ર','समयक्षेत्र'],examConfirm:['I confirm the exam date and topics. These are not assignment deadlines.','પરીક્ષાની તારીખ અને મુદ્દાઓની પુષ્ટિ કરું છું. આ અસાઇનમેન્ટની છેલ્લી તારીખ નથી.','परीक्षा की तारीख और विषयों की पुष्टि करता/करती हूँ। यह असाइनमेंट की समयसीमा नहीं है।'],preview:['Preview plan','યોજના જુઓ','योजना देखें'],add:['Add this plan to Planner','Plannerમાં યોજના ઉમેરો','योजना Planner में जोड़ें'],
estimate:['Estimated blocks, with breaks. Task times are 18:00 in your chosen timezone; adjust them in Planner. The day before the exam is left for rest or light review.','વિરામ સાથે અંદાજિત અભ્યાસ સમય. કામનો સમય પસંદ કરેલા સમયક્ષેત્રમાં 18:00 છે; Plannerમાં બદલી શકો છો. પરીક્ષા પહેલાંનો દિવસ આરામ કે હળવા પુનરાવર્તન માટે ખાલી છે.','ब्रेक सहित अनुमानित अध्ययन समय। काम चुने समयक्षेत्र में 18:00 बजे तय हैं; Planner में बदल सकते हैं। परीक्षा से पहले का दिन आराम या हल्के अभ्यास के लिए खाली है।'],limited:['This budget covers only part of recall, practice and revision. Reduce topics or allow more time.','આ સમયમાં યાદ કરવું, પ્રેક્ટિસ અને પુનરાવર્તન બધું પૂરું નહીં થાય. મુદ્દા ઓછા કરો અથવા સમય વધારો.','इस समय में याद करना, अभ्यास और दोहराना पूरा नहीं होगा। विषय घटाएँ या समय बढ़ाएँ।'],planSaved:['Plan saved to Planner.','Plannerમાં યોજના સેવ થઈ.','योजना Planner में सेव हुई।'],noPlans:['No exam plans yet.','હજુ પરીક્ષાની યોજના નથી.','अभी कोई परीक्षा योजना नहीं है।'],retained:['Remove this plan? Its tasks stay in Planner for you to keep, change or delete.','યોજના કાઢવી છે? તેના કામ Plannerમાં રહેશે; રાખી, બદલી કે કાઢી શકશો.','योजना हटाएँ? उसके काम Planner में रहेंगे; उन्हें रख, बदल या हटा सकते हैं।'],recall:['Recall','યાદ કરો','याद करें'],practice:['Practice','પ્રેક્ટિસ','अभ्यास'],revision:['Revision','પુનરાવર્તન','दोहराएँ'],rest:['Rest / optional light review','આરામ / વૈકલ્પિક હળવું પુનરાવર્તન','आराम / वैकल्पिक हल्का अभ्यास'],past:['Review older information before permitting it again.','ફરી મંજૂરી આપતા પહેલાં જૂની માહિતી તપાસો.','फिर अनुमति देने से पहले पुरानी जानकारी जाँचें।'],error:['Could not complete this action. Your entries are still here; retry.','કામ પૂરું ન થયું. તમારી વિગતો અહીં છે; ફરી પ્રયાસ કરો.','काम पूरा नहीं हुआ। आपकी जानकारी यहाँ है; फिर कोशिश करें।']
};
const text=key=>(words[key]||[key,key,key])[({en:0,gu:1,hi:2})[document.documentElement.lang]||0];
const fields={care:['conditions','allergies','clinician_instructions','food_preferences','accessibility'],study:['level','subjects','goal','available_time','tone']};
function node(tag,value,cls){const n=document.createElement(tag);if(value)n.textContent=value;if(cls)n.className=cls;return n}
function button(label,fn){const n=node('button',label,'dw-button');n.type='button';n.onclick=fn;return n}
function field(label,type,value){const wrap=node('label',label,'dw-field'),el=node(type==='textarea'?'textarea':'input');if(type!=='textarea')el.type=type;el.value=value||'';wrap.append(el);return {wrap,el}}
function check(label){const wrap=node('label',null,'dw-check'),el=node('input');el.type='checkbox';wrap.append(el,node('span',label));return {wrap,el}}
function modal(title){const d=node('dialog',null,'dw-dialog'),head=node('header',null,'dw-dialog-head'),h=node('h2',title);h.id='personal-'+crypto.randomUUID();d.setAttribute('aria-labelledby',h.id);d.setAttribute('data-user-content','');d.style.overflowWrap='anywhere';head.append(h,button(text('close'),()=>{if(!d.dataset.saving)d.close()}));d.append(head);d.addEventListener('cancel',e=>{if(d.dataset.saving)e.preventDefault()});d.addEventListener('close',()=>d.remove());document.body.append(d);d.showModal();return d}
function errorNode(){const n=node('p',null,'dw-error');n.setAttribute('role','alert');return n}
async function request(path,method,body){return api(path,{method,body:JSON.stringify(body)})}
async function run(control,error,fn){if(control.disabled)return;control.disabled=true;error.textContent='';try{await fn()}catch(e){error.textContent=e.message||text('error')}finally{control.disabled=false}}
async function lockDialog(d,fn){d.dataset.saving='true';const controls=[...d.querySelectorAll('input,textarea,button')].map(n=>[n,n.disabled]);controls.forEach(([n])=>n.disabled=true);try{return await fn()}finally{delete d.dataset.saving;controls.forEach(([n,disabled])=>n.disabled=disabled)}}
async function profiles(category){
 const d=modal(text(category)),list=node('div'),error=errorNode();d.append(node('p',text('boundary'),'dw-muted'),list,error);
 const load=async()=>{list.textContent=text('loading');const data=await api('/api/personal-context');if(!d.isConnected)return;list.replaceChildren();
 const switches=node('div',null,'dw-actions');for(const kind of Object.keys(fields))switches.append(button(text(kind),()=>{d.close();profiles(kind)}));list.append(switches);
 for(const key of fields[category]){const saved=data.fields.find(x=>x.category===category&&x.field===key),row=node('article',null,'dw-panel');row.append(node('h3',text(key)),node('p',saved?.value||text('empty')));if(saved){row.append(node('small',text(saved.use_in_ai?'permitted':'private')+' · '+text('last')+': '+new Date(saved.reviewed_at).toLocaleDateString(document.documentElement.lang)));if(Date.now()-new Date(saved.reviewed_at)>90*86400000)row.append(node('p',text('past'),'dw-muted'))}row.append(button(text('review'),()=>editField(category,key,saved,load)));list.append(row)}
 const revoke=button(text('revoke'),()=>run(revoke,error,async()=>{await request('/api/personal-context/revoke','POST',{});notify(text('revoked'));await load()}));list.append(revoke)};
 try{await load()}catch(e){list.textContent='';error.textContent=e.message||text('error');const retry=button(text('retry'),()=>run(retry,error,load));d.append(retry)}
}
function editField(category,key,saved,reload){
 const d=modal(text(key)),form=node('form',null,'dw-form'),value=field(text(key),'textarea',saved?.value),consent=check(text('confirm')),allow=check(text('allow')),error=errorNode();value.el.required=true;value.el.maxLength=1500;allow.el.checked=Boolean(saved?.use_in_ai);consent.el.required=true;
 if(category==='study'&&key==='tone'){const select=node('select');for(const [key,label] of [['Gentle',text('gentle')],['Direct and respectful',text('direct')]]){const option=node('option',label);option.value=key;select.append(option)}if(saved?.value&&!['Gentle','Direct and respectful'].includes(saved.value)){const custom=node('option',saved.value);custom.value=saved.value;select.append(custom)}select.value=saved?.value||'Gentle';value.el.replaceWith(select);value.el=select;select.required=true;}
 const save=node('button',text('save'),'dw-button dw-primary');save.type='submit';form.append(value.wrap,node('p',text('source'),'dw-muted'),allow.wrap,node('p',text('boundary'),'dw-muted'),consent.wrap,error,save);d.append(form);
 form.onsubmit=e=>{e.preventDefault();const payload={value:value.el.value,version:saved?.version||0,confirmed:consent.el.checked,use_in_ai:allow.el.checked};run(save,error,()=>lockDialog(d,async()=>{await request('/api/personal-context/'+category+'/'+key,'PUT',payload);d.close();notify(text('saved'));await reload()}))};
 if(saved){let confirmed=false;const remove=button(text('remove'),()=>{if(!confirmed){confirmed=true;remove.textContent=text('deleteConfirm');return}run(remove,error,()=>lockDialog(d,async()=>{await request('/api/personal-context/'+category+'/'+key,'DELETE',{version:saved.version});d.close();notify(text('deleted'));await reload()}))});form.append(remove)}
}
function replanExam(plan,onSaved=async()=>{}){
 const d=modal(text('replan')),consent=check(text('progress')),error=errorNode(),results=node('div'),examDate=field(text('date'),'date',plan.exam_date);
 d.append(node('b',plan.title),node('p',text('replanNote'),'dw-muted'),examDate.wrap,consent.wrap,error,results);
 const previewButton=button(text('preview'),()=>run(previewButton,error,()=>lockDialog(d,async()=>{
  results.replaceChildren();
  const data=await request('/api/exam-plans/'+plan.id+'/replan/preview','POST',{confirmed:consent.el.checked,exam_date:examDate.el.value});
  const p=data.plan,list=node('ol');
  for(const item of p.items)list.append(node('li',item.title+' · '+new Date(item.from).toLocaleDateString(document.documentElement.lang)+' → '+new Date(item.due_at).toLocaleDateString(document.documentElement.lang,{timeZone:plan.timezone})));
  results.append(list,node('p',text('unscheduled')+': '+p.unscheduled),node('p',text('preserved')+': '+p.preserved.length),node('p',text('date')+': '+p.exam_date),node('p',text('rest')+': '+p.rest_date),node('p',text('outsideWindow')+': '+p.outside_window));
  if(!p.items.length&&!p.date_changed){results.append(node('p',text('noMoves')));return}
  const apply=button(text('applyReplan'),()=>run(apply,error,()=>lockDialog(d,async()=>{
   await request('/api/exam-plans/'+plan.id+'/replan/apply','POST',{confirmed:consent.el.checked,preview_token:p.preview_token,exam_date:examDate.el.value});
   d.close();notify(text('saved'));await refreshTasks();await onSaved();
  })));results.append(apply);
 })));
 consent.el.onchange=examDate.el.oninput=()=>results.replaceChildren();d.append(previewButton);
}
async function exams(){
 const d=modal(text('exams')),form=node('form',null,'dw-form'),title=field(text('title'),'text'),date=field(text('date'),'date'),topics=field(text('topics'),'textarea'),minutes=field(text('minutes'),'number','30'),zone=field(text('zone'),'text',Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'),confirm=check(text('examConfirm')),error=errorNode(),preview=node('div'),saved=node('div');title.el.maxLength=80;minutes.el.min=10;minutes.el.max=240;topics.el.maxLength=6060;for(const x of [title,date,topics,minutes,zone])x.el.required=true;confirm.el.required=true;
 const submit=node('button',text('preview'),'dw-button dw-primary');submit.type='submit';form.append(title.wrap,date.wrap,topics.wrap,minutes.wrap,zone.wrap,confirm.wrap,error,submit);d.append(form,preview,saved);let revision=0;
 form.addEventListener('input',()=>{revision++;preview.replaceChildren()});
 form.onsubmit=e=>{e.preventDefault();const token=++revision,payload={title:title.el.value,exam_date:date.el.value,topics:topics.el.value.split('\n').map(x=>x.trim()).filter(Boolean),daily_minutes:Number(minutes.el.value),timezone:zone.el.value,confirmed:confirm.el.checked,client_id:crypto.randomUUID()};run(submit,error,async()=>{const data=await request('/api/exam-plans/preview','POST',payload);if(token!==revision||!d.isConnected)return;payload.preview_token=data.plan.preview_token;preview.replaceChildren(node('p',text('estimate'),'dw-muted'));if(data.plan.coverage_limited)preview.append(node('p',text('limited'),'dw-error'));const list=node('ol');for(const item of data.plan.items)list.append(node('li',item.date+' · '+text(item.phase)+': '+item.topic+' · '+item.minutes+' min'));preview.append(list,node('p',data.plan.rest_date+' · '+text('rest')));const add=button(text('add'),()=>run(add,error,()=>lockDialog(d,async()=>{await request('/api/exam-plans','POST',payload);d.close();notify(text('planSaved'));await refreshTasks();openView('tasks')})));preview.append(add)})};
 const loadSaved=async()=>{const data=await api('/api/exam-plans');if(!d.isConnected)return;saved.replaceChildren();if(!data.plans.length)saved.append(node('p',text('noPlans'),'dw-muted'));for(const plan of data.plans){const row=node('article',null,'dw-panel');row.append(node('b',plan.title+' · '+plan.exam_date));let confirmed=false;const remove=button(text('remove'),()=>{if(!confirmed){confirmed=true;row.append(node('p',text('retained')));return}run(remove,error,async()=>{await request('/api/exam-plans/'+plan.id,'DELETE',{});await loadSaved()})});row.append(button(text('replan'),()=>replanExam(plan,loadSaved)),remove);saved.append(row)}};
 try{await loadSaved()}catch(e){error.textContent=e.message||text('error');const retry=button(text('retry'),()=>run(retry,error,loadSaved));saved.append(retry)}
}
function labels(){document.querySelectorAll('[data-personal-label]').forEach(n=>n.textContent=text(n.dataset.personalLabel))}
function connect(options){({api,notify,openView,refreshTasks}=options);document.querySelectorAll('[data-personal-context]').forEach(b=>b.onclick=()=>profiles(b.dataset.personalContext));document.querySelectorAll('[data-exam-plans]').forEach(b=>b.onclick=exams);labels()}
new MutationObserver(labels).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
window.SaathiPersonal={connect};
})();
