CREATE TABLE IF NOT EXISTS chat_context_permissions (
 user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
 tasks BOOLEAN NOT NULL DEFAULT FALSE, reminders BOOLEAN NOT NULL DEFAULT FALSE,
 classroom BOOLEAN NOT NULL DEFAULT FALSE, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS chat_action_receipts (
 message_id INTEGER PRIMARY KEY REFERENCES messages(id) ON DELETE CASCADE,
 user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 kind TEXT NOT NULL CHECK(kind IN ('task','reminder','note','memory','habit','journal','checkin')),
 resource_id BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS background_alert_runs (name TEXT PRIMARY KEY,last_run TIMESTAMPTZ NOT NULL,sent INTEGER NOT NULL DEFAULT 0,failed INTEGER NOT NULL DEFAULT 0);
