ALTER TABLE chat_context_permissions
 ADD COLUMN IF NOT EXISTS notes BOOLEAN NOT NULL DEFAULT FALSE,
 ADD COLUMN IF NOT EXISTS habits BOOLEAN NOT NULL DEFAULT FALSE,
 ADD COLUMN IF NOT EXISTS study BOOLEAN NOT NULL DEFAULT FALSE,
 ADD COLUMN IF NOT EXISTS exams BOOLEAN NOT NULL DEFAULT FALSE;
